const data = [
  {word:"acabar", definition:"to finish, to end, to complete"},
  {word:"andar", definition:"to walk"},
  {word:"aprender", definition:"to learn"},
  {word:"caer/caerse", definition:"to fall (to fall down, to tumble)"},
  {word:"cantar", definition:"to sing"},
  {word:"comer", definition:"to eat"},
  {word:"comprar", definition:"to buy, to purchase"},
  {word:"conducir", definition:"to lead, to conduct, to drive"},
  {word:"contar", definition:"to count, to relate, to tell"},
  {word:"creer", definition:"to believe"},
  {word:"dar", definition:"to give"},
  {word:"deber", definition:"to owe, must, ought"},
  {word:"decir", definition:"to say, to tell"},
  {word:"dormir", definition:"to sleep"},
  {word:"entrar", definition:"to enter (to go in, to come in)"},
  {word:"escribir", definition:"to write"},
  {word:"estar", definition:"to be"},
  {word:"estudiar", definition:"to study"},
  {word:"gustar", definition:"to like (to be pleasing to)"},
  {word:"haber", definition:"to have"},
  {word:"hablar", definition:"to talk, to speak"},
  {word:"hacer", definition:"to do, to make"},
  {word:"ir/irse", definition:"to go/to go away"},
  {word:"leer", definition:"to read"},
  {word:"llamar/llamarse", definition:"to call, to name/to be called/named"},
  {word:"llevar", definition:"to carry away, to take away, to wear"},
  {word:"mirar/mirarse", definition:"to look, to look at, to watch"},
  {word:"oír", definition:"to hear"},
  {word:"pagar", definition:"to pay"},
  {word:"pensar", definition:"to think"},
  {word:"perder", definition:"to lose"},
  {word:"poder", definition:"to be able, can"},
  {word:"poner/ponerse", definition:"to put, to place, to turn on (TV, radio)/to put on (clothing), to become, to set (of sun)"},
  {word:"quedarse", definition:"to remain, to stay"},
  {word:"querer", definition:"to want, to wish"},
  {word:"saber", definition:"to know, to know how"},
  {word:"salir", definition:"to go out, to leave"},
  {word:"sentir/sentirse", definition:"to feel sorry, to regret, to feel"},
  {word:"ser", definition:"to be"},
  {word:"tener", definition:"to have, to hold"},
  {word:"tomar", definition:"to take, to have (something to eat or drink)"},
  {word:"traer", definition:"to bring"},
  {word:"venir", definition:"to come"},
  {word:"ver", definition:"to see"},
  {word:"vivir", definition:"to live"},
  {word:"volver", definition:"to return, to go back"},
  {word:"comenzar", definition:"to begin, to start, to commence"},
  {word:"conocer", definition:"to know, to be acquainted with"},
  {word:"construir", definition:"to construct, to build"}
];